name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: '.commitlintrc.js'

  build:
    needs: commitlint
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # Fetch origin/master so that we have a base to run the affected commands against
      - name: Fetch origin/master
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install dependencies
        run: npm install

      - name: Format
        run: npm run format:check -- --base=origin/master

      - name: Lint
        run: npm run affected:lint -- --base=origin/master

      - name: Build
        run: npm run affected:build -- --base=origin/master

  test:
    needs: build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # Fetch origin/master so that we have a base to run the affected commands against
      - name: Fetch origin/master
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run affected:test -- --base=origin/master

  e2e-test:
    needs: build

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14.x, 15.x]
        dotnet: ['5.0.x']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      # Fetch origin/master so that we have a base to run the affected commands against
      - name: Fetch origin/master
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run affected:e2e -- --base=origin/master
